//
// Alias.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Alias: Codable {

    public var createdAt: Date
    public var emailAddress: String
    public var id: UUID?
    public var inboxId: UUID?
    public var name: String?
    public var proxied: Bool?
    public var updatedAt: Date
    public var userId: UUID?

    public init(createdAt: Date, emailAddress: String, id: UUID? = nil, inboxId: UUID? = nil, name: String? = nil, proxied: Bool? = nil, updatedAt: Date, userId: UUID? = nil) {
        self.createdAt = createdAt
        self.emailAddress = emailAddress
        self.id = id
        self.inboxId = inboxId
        self.name = name
        self.proxied = proxied
        self.updatedAt = updatedAt
        self.userId = userId
    }

}

