//
// AttachmentMetaData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Meta data associated with an attachment. Attachments are stored as byte blobs so the meta data is stored separately. */
public struct AttachmentMetaData: Codable {

    /** Size of attachment in bytes */
    public var contentLength: Int64?
    /** Content type of attachment */
    public var contentType: String?
    /** ID of attachment */
    public var id: String?
    /** Name of attachment */
    public var name: String?

    public init(contentLength: Int64? = nil, contentType: String? = nil, id: String? = nil, name: String? = nil) {
        self.contentLength = contentLength
        self.contentType = contentType
        self.id = id
        self.name = name
    }

}

