//
// ContactProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContactProjection: Codable {

    public var company: String?
    public var createdAt: Date
    public var firstName: String?
    public var id: UUID
    public var lastName: String?
    public var optOut: Bool?

    public init(company: String? = nil, createdAt: Date, firstName: String? = nil, id: UUID, lastName: String? = nil, optOut: Bool? = nil) {
        self.company = company
        self.createdAt = createdAt
        self.firstName = firstName
        self.id = id
        self.lastName = lastName
        self.optOut = optOut
    }

}

