//
// CreateDomainOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Options for creating a domain to use with MailSlurp. You must have ownership access to this domain in order to verify it. */
public struct CreateDomainOptions: Codable {

    /** The top level domain you wish to use with MailSlurp */
    public var domain: String?

    public init(domain: String? = nil) {
        self.domain = domain
    }

}

