//
// DomainPreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Preview object for domain entity */
public struct DomainPreview: Codable {

    public var createdAt: Date
    public var domain: String
    public var id: UUID

    public init(createdAt: Date, domain: String, id: UUID) {
        self.createdAt = createdAt
        self.domain = domain
        self.id = id
    }

}

