//
// EmailProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A compact representation of a full email. Used in list endpoints to keep response sizes low. Body and attachments are not included. To get all fields of the email use the &#x60;getEmail&#x60; method with the email projection&#39;s ID. See &#x60;EmailDto&#x60; for documentation on projection properties. */
public struct EmailProjection: Codable {

    public var attachments: [String]?
    public var bcc: [String]?
    public var cc: [String]?
    public var createdAt: Date
    public var from: String?
    public var id: UUID
    public var inboxId: UUID
    public var read: Bool?
    public var subject: String?
    public var to: [String]

    public init(attachments: [String]? = nil, bcc: [String]? = nil, cc: [String]? = nil, createdAt: Date, from: String? = nil, id: UUID, inboxId: UUID, read: Bool? = nil, subject: String? = nil, to: [String]) {
        self.attachments = attachments
        self.bcc = bcc
        self.cc = cc
        self.createdAt = createdAt
        self.from = from
        self.id = id
        self.inboxId = inboxId
        self.read = read
        self.subject = subject
        self.to = to
    }

}

