//
// GroupContactsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GroupContactsDto: Codable {

    public var contacts: [ContactDto]
    public var group: GroupDto

    public init(contacts: [ContactDto], group: GroupDto) {
        self.contacts = contacts
        self.group = group
    }

}

