//
// GroupDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GroupDto: Codable {

    public var createdAt: Date
    public var description: String?
    public var id: UUID
    public var name: String

    public init(createdAt: Date, description: String? = nil, id: UUID, name: String) {
        self.createdAt = createdAt
        self.description = description
        self.id = id
        self.name = name
    }

}

