//
// Pageable.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Pageable: Codable {

    public var offset: Int64?
    public var pageNumber: Int?
    public var pageSize: Int?
    public var paged: Bool?
    public var sort: Sort?
    public var unpaged: Bool?

    public init(offset: Int64? = nil, pageNumber: Int? = nil, pageSize: Int? = nil, paged: Bool? = nil, sort: Sort? = nil, unpaged: Bool? = nil) {
        self.offset = offset
        self.pageNumber = pageNumber
        self.pageSize = pageSize
        self.paged = paged
        self.sort = sort
        self.unpaged = unpaged
    }

}

