//
// RawEmailJson.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RawEmailJson: Codable {

    public var content: String

    public init(content: String) {
        self.content = content
    }

}

