//
// SimpleSendEmailOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SimpleSendEmailOptions: Codable {

    /** Body of the email message. Supports HTML */
    public var body: String?
    /** ID of inbox to send from */
    public var senderId: UUID?
    /** Subject line of the email */
    public var subject: String?
    /** Email address to send to */
    public var to: String?

    public init(body: String? = nil, senderId: UUID? = nil, subject: String? = nil, to: String? = nil) {
        self.body = body
        self.senderId = senderId
        self.subject = subject
        self.to = to
    }

}

