//
// Sort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Sort: Codable {

    public var empty: Bool?
    public var sorted: Bool?
    public var unsorted: Bool?

    public init(empty: Bool? = nil, sorted: Bool? = nil, unsorted: Bool? = nil) {
        self.empty = empty
        self.sorted = sorted
        self.unsorted = unsorted
    }

}

