//
// TemplateProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TemplateProjection: Codable {

    public var createdAt: Date
    public var id: UUID
    public var name: String
    public var updatedAt: Date
    public var variables: [String]

    public init(createdAt: Date, id: UUID, name: String, updatedAt: Date, variables: [String]) {
        self.createdAt = createdAt
        self.id = id
        self.name = name
        self.updatedAt = updatedAt
        self.variables = variables
    }

}

