//
// TemplateDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TemplateDto: Codable {

    public var content: String
    public var createdAt: Date
    public var id: UUID
    public var name: String
    public var variables: [TemplateVariable]

    public init(content: String, createdAt: Date, id: UUID, name: String, variables: [TemplateVariable]) {
        self.content = content
        self.createdAt = createdAt
        self.id = id
        self.name = name
        self.variables = variables
    }

}

