//
// UnreadCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UnreadCount: Codable {

    public var count: Int64

    public init(count: Int64) {
        self.count = count
    }

}

