//
// UpdateInboxOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Options for updating inbox properties */
public struct UpdateInboxOptions: Codable {

    /** Optional description of an inbox for labelling purposes */
    public var description: String?
    /** When, if ever, will the inbox expire and be deleted. If null then this inbox is permanent and the emails in it won&#39;t be deleted. Timestamp passed as string. */
    public var expiresAt: Date?
    /** Is the inbox favourited */
    public var favourite: Bool?
    /** Optional name of the inbox. Displayed in the dashboard for easier search */
    public var name: String?
    /** Tags that inbox has been tagged with */
    public var tags: [String]?

    public init(description: String? = nil, expiresAt: Date? = nil, favourite: Bool? = nil, name: String? = nil, tags: [String]? = nil) {
        self.description = description
        self.expiresAt = expiresAt
        self.favourite = favourite
        self.name = name
        self.tags = tags
    }

}

