//
// WebhookTestResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct WebhookTestResponse: Codable {

    public var message: String?
    public var statusCode: Int?

    public init(message: String? = nil, statusCode: Int? = nil) {
        self.message = message
        self.statusCode = statusCode
    }

}

