//
// WebhookProjection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Representation of a webhook */
public struct WebhookProjection: Codable {

    public var createdAt: Date
    public var id: UUID
    public var inboxId: UUID
    public var name: String?
    public var updatedAt: Date
    public var url: String

    public init(createdAt: Date, id: UUID, inboxId: UUID, name: String? = nil, updatedAt: Date, url: String) {
        self.createdAt = createdAt
        self.id = id
        self.inboxId = inboxId
        self.name = name
        self.updatedAt = updatedAt
        self.url = url
    }

}

